build: aggressive refactoring

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,49 +1,56 @@
 #!/usr/bin/env fish
-#│
-#│ Usage
-#│ ‾‾‾‾‾
-#│ → build [test] [push] (ignores unrecognized commands)
-#│ → build then test and push
-#│
-#│ Source structure
-#│ .
-#│ ├── assets
-#│ │   ├── coffee
-#│ │   │   └── script.coffee
-#│ │   ├── fonts
-#│ │   │   └── menlo.ttf
-#│ │   ├── haml
-#│ │   │   └── helpers.rb
-#│ │   ├── images
-#│ │   │   └── favicon.ico
-#│ │   └── sass
-#│ │       ├── solarized.sass
-#│ │       └── style.sass
-#│ ├── build
-#│ ├── content
-#│ ├── git
-#│ │   └── hooks
-#│ │       └── pre-push
-#│ ├── layouts
-#│ │   ├── base.haml
-#│ │   ├── page.haml
-#│ │   └── post.haml
-#│ ├── nginx.conf
-#│ └── CNAME
-#│
-#│ Building
-#│ ‾‾‾‾‾‾‾‾
-#│  . Main
-#│ 1. Working directory
-#│ 2. Haml to HTML
-#│ 3. Sass to CSS
-#│ 4. CoffeeScript to JavaScript
-#│ 5. Kakoune filters
-#│ 6. Index page
-#│ 7. Build pages
-#│ 8. Deployment
-#│  . Utility
-#│
+
+set LOG (mktemp)
+
+set usage 'usage: build [now] [test] [push] (ignores unrecognized commands)
+
+Source structure
+.
+├── assets
+│   ├── coffee
+│   │   └── script.coffee
+│   ├── fonts
+│   │   └── menlo.ttf
+│   ├── haml
+│   │   └── helpers.rb
+│   ├── images
+│   │   └── favicon.ico
+│   └── sass
+│       ├── solarized.sass
+│       └── style.sass
+├── build
+├── content
+├── git
+│   └── hooks
+│       └── pre-push
+├── layouts
+│   ├── base.haml
+│   ├── page.haml
+│   └── post.haml
+├── nginx.conf
+└── CNAME
+
+Building
+‾‾‾‾‾‾‾‾
+ . Main
+1. Working directory
+2. Haml to HTML
+3. Sass to CSS
+4. CoffeeScript to JavaScript
+5. Kakoune filters
+6. Index page
+7. Build pages
+8. Deployment
+ . Utility
+'
+
+if not echo $argv | grep .                                            >/dev/null
+  echo $usage; and exit 1
+end
+
+if echo $argv | grep help                                             >/dev/null
+  echo $usage; and exit 0
+end
 
 function main
 
@@ -68,43 +75,61 @@ function main
 
   # 2. Haml to HTML ────────────────────────────────────────────────────────────
 
-  set   base_html   base.html
-  set   page_html   page.html
-  set   post_html   post.html
-  set disqus_html disqus.html
+  printf 'Compiling templates…'
 
-  haml --require ./assets/haml/helpers layouts/{}base.haml   $base_html
-  haml --require ./assets/haml/helpers layouts/{}page.haml   $page_html
-  haml --require ./assets/haml/helpers layouts/{}post.haml   $post_html
-  haml --require ./assets/haml/helpers layouts/disqus.haml $disqus_html
+  begin
+    set   base_html   base.html
+    set   page_html   page.html
+    set   post_html   post.html
+    set disqus_html disqus.html
 
-  copy   $page_html   $page_html.template
-  copy   $post_html   $post_html.template
-  copy $disqus_html $disqus_html.template
+    haml --require ./assets/haml/helpers layouts/{}base.haml   $base_html
+    haml --require ./assets/haml/helpers layouts/{}page.haml   $page_html
+    haml --require ./assets/haml/helpers layouts/{}post.haml   $post_html
+    haml --require ./assets/haml/helpers layouts/disqus.haml $disqus_html
 
-  include '$body$' $base_html $page_html.template                                           >   $page_html
-  include '$body$' $base_html $page_html.template $post_html.template                       >   $post_html
-  include '$body$' $base_html $page_html.template $post_html.template $disqus_html.template > $disqus_html
+    copy   $page_html   $page_html.template
+    copy   $post_html   $post_html.template
+    copy $disqus_html $disqus_html.template
+
+    include '$body$' $base_html $page_html.template                                           >   $page_html
+    include '$body$' $base_html $page_html.template $post_html.template                       >   $post_html
+    include '$body$' $base_html $page_html.template $post_html.template $disqus_html.template > $disqus_html
+  end                                                                            1> /dev/null\
+                                                                                 2> $LOG
+  pass < $LOG
 
   # 3. Sass to CSS ─────────────────────────────────────────────────────────────
 
-  echo 'preferred_syntax = :sass
-        css_dir          = "site/css"
-        sass_dir         = "assets/sass"
-        images_dir       = "images"
-        fonts_dir        = "fonts"
-       ' > config.rb
+  printf 'Compiling style sheets…'
 
-  compass compile
+  begin
+    echo 'preferred_syntax = :sass
+          css_dir          = "site/css"
+          sass_dir         = "assets/sass"
+          images_dir       = "images"
+          fonts_dir        = "fonts"
+         ' > config.rb
+
+    compass compile
+  end                                                                            1> /dev/null\
+                                                                                 2> $LOG
+  pass < $LOG
 
   # 4. Coffee to JS ────────────────────────────────────────────────────────────
 
-  set coffee assets/coffee ; and make $coffee
-  set js     assets/js     ; and make $js
+  printf 'Compiling JS…'
 
-  coffee --compile $coffee
+  begin
+    set coffee assets/coffee ; and make $coffee
+    set js     assets/js     ; and make $js
 
-  mv $coffee/*.js $js
+    coffee --compile $coffee
+
+    mv $coffee/*.js $js
+  end                                                                            1> /dev/null\
+                                                                                 2> $LOG
+  pass < $LOG
 
   # 5. Kakoune filters ─────────────────────────────────────────────────────────
 
@@ -133,177 +158,200 @@ function main
 
   # 6.1 List page
 
-  set index_page tmp/index.md
-  set list_page  tmp/list.md
+  printf 'Listing pages…'
 
-  for source in (files content)
+  begin
+    set index_page tmp/index.md
+    set list_page  tmp/list.md
 
-    set output (echo $source | sed s/content//';'s/.md'$'/.html/)
+    for source in (files content)
 
-    if echo $source | egrep '(README|READING|HOWTO|.sh$)'
-      continue
+      set output (echo $source | sed s/content//';'s/.md'$'/.html/)
+
+      if echo $source | egrep '(README|READING|HOWTO|.sh$)'
+        continue
+      end
+
+      set title (head -1 $source)
+
+      set link (echo $output | replace .html '' | esed s/'(main|index)$'//)
+
+      set commit (git log -1 --format=%h $source)
+
+      set commit_timestamp (git log -1 --format=%ct $source)
+
+      set commit_iso_date (git log -1 --format=%ci $source)
+
+      echo "$commit_timestamp<h2 style=display:inline>[$title]($link)</h2> <a class=timeago title='View Commit' href=https://github.com/alexherbo2/alexherbo2.github.io/commit/$commit><time class=timeago datetime='"$commit_iso_date"'></time></a><br>" >> $list_page.lock
     end
 
-    set title (head -1 $source)
-
-    set link (echo $output | replace .html '' | esed s/'(main|index)$'//)
-
-    set commit (git log -1 --format=%h $source)
-
-    set commit_timestamp (git log -1 --format=%ct $source)
-
-    set commit_iso_date (git log -1 --format=%ci $source)
-
-    echo "$commit_timestamp<h2 style=display:inline>[$title]($link)</h2> <a class=timeago title='View Commit' href=https://github.com/alexherbo2/alexherbo2.github.io/commit/$commit><time class=timeago datetime='"$commit_iso_date"'></time></a><br>" >> $list_page.lock
-  end
-
-  sort --reverse $list_page.lock | esed s/'^([0-9]+ ?)+'// > $list_page
+    sort --reverse $list_page.lock | esed s/'^([0-9]+ ?)+'// > $list_page
+  end                                                                            1> /dev/null\
+                                                                                 2> $LOG
+  pass < $LOG
 
   # 7. Build pages ─────────────────────────────────────────────────────────────
 
-  # fish sucks: Cannot save multi-line output in a variable
-  # https://github.com/fish-shell/fish-shell/issues/159
-  sh -c 'replace "\$list\$"    "<div style=white-space:nowrap>`cat     '$list_page'`</div>" -- content/README.md'
-  sh -c 'replace "\$reading\$" "<pre style=border:0          >`cat  content/READING`</pre>" -- content/README.md'
+  printf 'Compiling pages…'
 
-  for source in (files content -name '*.sh')
-    set output (echo $source | replace .sh .md)
-    cd (dirname $source); sh (basename $source) > (basename $output)
-    cd -
-  end
+  begin
+    # fish sucks: Cannot save multi-line output in a variable
+    # https://github.com/fish-shell/fish-shell/issues/159
+    sh -c 'replace "\$list\$"    "<div style=white-space:nowrap>`cat     '$list_page'`</div>" -- content/README.md'
+    sh -c 'replace "\$reading\$" "<pre style=border:0          >`cat  content/READING`</pre>" -- content/README.md'
 
-  for source in (files content -name '*.md')
+    for source in (files content -name '*.sh')
+      set output (echo $source | replace .sh .md)
+      cd (dirname $source); sh (basename $source) > (basename $output)
+      cd -
+    end
 
-    set output (echo $source | esed s/content/site/';'s/.md'$'/.html/';'s/'(main|README)'/index/)
+    for source in (files content -name '*.md')
 
-    make (dirname $output)
+      set output (echo $source | esed s/content/site/';'s/.md'$'/.html/';'s/'(main|README)'/index/)
 
-    kak -n -e edit\ $source';'"$kak_filters"
+      make (dirname $output)
 
-    set title (head -1 $source)
+      kak -n -e edit\ $source';'"$kak_filters"
 
-    set path (echo $source | replace content/ '')
+      set title (head -1 $source)
 
-    set commit (git log -1 --format=%h $source)
+      set path (echo $source | replace content/ '')
 
-    set commit_timestamp (git log -1 --format=%ct $source)
+      set commit (git log -1 --format=%h $source)
 
-    set commit_iso_date (git log -1 --format=%ci $source)
+      set commit_timestamp (git log -1 --format=%ct $source)
 
-    set commit_date (date --date @$commit_timestamp +'%d %b %Y')
+      set commit_iso_date (git log -1 --format=%ci $source)
 
-    # Remove title
-    sed --in-place 1,2d $source
+      set commit_date (date --date @$commit_timestamp +'%d %b %Y' 2>/dev/null)
 
-    # Replace shell code snippets with Bash
-    # Reason: shell is not recognized
-    sub s/'```( *)sh'/'```\1bash'/ $source
+      # Remove title
+      sed --in-place 1,2d $source
 
-    if echo $source | egrep '(README|READING)'
-      set template $page_html.copy; cp $page_html $template
-    else
-      if not grep comment-identifier $source
-        set template $post_html.copy; cp $post_html $template
+      # Replace shell code snippets with Bash
+      # Reason: shell is not recognized
+      sub s/'```( *)sh'/'```\1bash'/ $source
+
+      if echo $source | egrep '(README|READING)'
+        set template $page_html.copy; cp $page_html $template
       else
-        set template $disqus_html.copy; cp $disqus_html $template
+        if not grep comment-identifier $source
+          set template $post_html.copy; cp $post_html $template
+        else
+          set template $disqus_html.copy; cp $disqus_html $template
+        end
       end
-    end
 
-    # Replace in place
-    replace '$path$'            "$path"            -- $template
-    replace '$commit$'          "$commit"          -- $template
-    replace '$commit-date$'     "$commit_date"     -- $template
-    replace '$commit-iso-date$' "$commit_iso_date" -- $template
+      # Replace in place
+      replace '$path$'            "$path"            -- $template
+      replace '$commit$'          "$commit"          -- $template
+      replace '$commit-date$'     "$commit_date"     -- $template
+      replace '$commit-iso-date$' "$commit_iso_date" -- $template
 
-    # Clickable URLs
-    # sub s_' (https?://\S+\.[a-z]+)'_' [\1](\1)'_g $source
+      # Clickable URLs
+      # sub s_' (https?://\S+\.[a-z]+)'_' [\1](\1)'_g $source
 
-    # Spotify
-    sub s+'^%spotify (.*)'+'<iframe src=https://embed.spotify.com/?uri=spotify:track:\1       width=300 height=080 frameborder=0></iframe>'+ $source
+      # Spotify
+      sub s+'^%spotify (.*)'+'<iframe src=https://embed.spotify.com/?uri=spotify:track:\1       width=300 height=080 frameborder=0></iframe>'+ $source
 
-    # YouTube
-    sub s+'^%youtube (.*)'+'<iframe src=https://youtube.com/embed/\1?theme=light\&color=white width=420 height=315 frameborder=0></iframe>'+ $source
+      # YouTube
+      sub s+'^%youtube (.*)'+'<iframe src=https://youtube.com/embed/\1?theme=light\&color=white width=420 height=315 frameborder=0></iframe>'+ $source
 
-    # Pandoc front matter
-    set   regexp_front_matter '^''%''[a-z]''+'
-    alias pandoc_front_matter "egrep '$regexp_front_matter' '$source'"
-    if pandoc_front_matter
+      # Pandoc front matter
+      set   regexp_front_matter '^''%''[a-z]''+'
+      alias pandoc_front_matter "egrep '$regexp_front_matter' '$source'"
+      if pandoc_front_matter
 
-      sub /"$regexp_front_matter"/d $source
-      for token in (pandoc_front_matter)
-        set key   (echo "$token" | tr --squeeze-repeats ' ' | cut --delimiter ' ' --fields 1 | cut --characters 2-)
-        set value (echo "$token" | tr --squeeze-repeats ' ' | cut --delimiter ' ' --fields                      2-)
+        sub /"$regexp_front_matter"/d $source
+        for token in (pandoc_front_matter)
+          set key   (echo "$token" | tr --squeeze-repeats ' ' | cut --delimiter ' ' --fields 1 | cut --characters 2-)
+          set value (echo "$token" | tr --squeeze-repeats ' ' | cut --delimiter ' ' --fields                      2-)
 
-        replace '$'$key'$' "$value" -- $template
+          replace '$'$key'$' "$value" -- $template
 
+        end
       end
+
+      # Pandoc title block
+      # % title
+      # % author(s)
+      # % date
+      sub "1i% $title\n%\n%\n" $source
+
+      # jQuery escaping
+      replace '$ ' '$$ ' -- $template
+      replace '$(' '$$(' -- $template
+
+      pandoc --template $template $source --output $output
+
+      # Pandoc + Haml(white space aware) = #fail
+      sub s/^' {2}'// $output
+
     end
-
-    # Pandoc title block
-    # % title
-    # % author(s)
-    # % date
-    sub "1i% $title\n%\n%\n" $source
-
-    # jQuery escaping
-    replace '$ ' '$$ ' -- $template
-    replace '$(' '$$(' -- $template
-
-    pandoc --template $template $source --output $output
-
-    # Pandoc + Haml(white space aware) = #fail
-    sub s/^' {2}'// $output
-
-  end
+  end                                                                            1> /dev/null\
+                                                                                 2> $LOG
+  pass < $LOG
 
   # 8. Deployment ──────────────────────────────────────────────────────────────
 
-  cd $repository
+  printf 'Deployment…'
 
-  git stash
-  git checkout master
+  begin
+    cd $repository
 
-  # Cleanup
-  git rm -r -f .
+    git stash
+    git checkout master
 
-  mv $work/assets/images .
-  mv $work/assets/fonts  .
-  mv $work/assets/js     .
-  mv $work/site/*        .
-  mv $work/CNAME         . # custom domain name
-  rm READING
+    # Cleanup
+    git rm -r -f .
 
-  git add --update
-  git add .
-  git amend --message=(date)
+    mv $work/assets/images .
+    mv $work/assets/fonts  .
+    mv $work/assets/js     .
+    mv $work/site/*        .
+    mv $work/CNAME         . # custom domain name
+    rm READING
 
-  if echo $argv | grep push
-    git push --force
-  end
+    git add --update
+    git add .
+    git amend --message=(date)
 
-  if echo $argv | grep test
-    make ~/log/nginx \
-         ~/www/alexherbo2.github.io
-    rsync --archive --compress --delete * ~/www/alexherbo2.github.io
-
-    if diff /etc/nginx/nginx.conf $work/nginx.conf | grep .
-      sudo mv /etc/nginx/nginx.conf{,~}
-      sudo mv $work/nginx.conf /etc/nginx
+    if echo $argv | grep push
+      git push --force
     end
 
-    if not systemctl list-units | grep nginx
-      sudo systemctl start nginx
-    end
-  end
+    if echo $argv | grep test
+      make ~/log/nginx \
+           ~/www/alexherbo2.github.io
+      rsync --archive --compress --delete * ~/www/alexherbo2.github.io
 
-  git checkout -
-  git stash apply
+      if diff /etc/nginx/nginx.conf $work/nginx.conf | grep .
+        sudo mv /etc/nginx/nginx.conf{,~}
+        sudo mv $work/nginx.conf /etc/nginx
+      end
+
+      if not systemctl list-units | grep nginx
+        sudo systemctl start nginx
+      end
+    end
+
+    git checkout -
+    git stash apply; or echo
+  end                                                                            1> /dev/null\
+                                                                                 2> $LOG
+  pass < $LOG
 
   notify-send alexherbo2.github.io
 
 end
 
 # Utility ├─────────────────────────────────────────────────────────────────────
+
+function pass
+  if test $status = 0 ; echo ✓ | colout . green normal ;
+  else                ; echo ✗ | colout . red   normal ; cat ; end
+end
 
 function make
   mkdir --parents $argv
@@ -347,6 +395,4 @@ function include
 end
 
 
-begin
-  main $argv
-end >/dev/null 2>&1
+main $argv
